apiVersion: v1
kind: Service
metadata:
  name: translator
  namespace: book-reader
  labels:
    app.kubernetes.io/name: translator
    app.kubernetes.io/component: translation
spec:
  type: ClusterIP
  selector:
    app: translator
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
